using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyTitleAttribute("Rhino.Mocks.Partial for Microsoft .NET Framework 3.5")]
[assembly: AssemblyDescriptionAttribute("Rhino Mocks 3.5 - Mocking Framework")]
[assembly: AssemblyCompanyAttribute("Rhino Tools Project")]
[assembly: AssemblyProductAttribute("Rhino.Mocks.Partial")]
[assembly: AssemblyCopyrightAttribute("Rhino Tools Project, original author or authors")]
[assembly: AssemblyVersionAttribute("3.5.0.1337")]
[assembly: AssemblyInformationalVersionAttribute("3.5.0.1928")]
[assembly: AssemblyFileVersionAttribute("3.5.0.1928")]
[assembly: AssemblyDelaySignAttribute(false)]

